# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
    ]
