# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=75)),
                ('Address', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=15)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientBank.Users')),
            ],
        ),
    ]
