# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientBank', '0003_auto_20170327_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationName', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientBank.Applications')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientBank.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientBank.Operations')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientBank.Users')),
            ],
        ),
    ]
