# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientBank', '0006_merge_20170403_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
