# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyName', models.CharField(max_length=100)),
                ('CurrencyCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationName', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=25)),
                ('ContractNumber', models.CharField(max_length=10)),
                ('CurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Applications')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=75)),
                ('Address', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=50)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Operations')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='useroperations',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Users'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Users'),
        ),
        migrations.AddField(
            model_name='products',
            name='StatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.ProductStatus'),
        ),
        migrations.AddField(
            model_name='products',
            name='TypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.ProductType'),
        ),
    ]
