# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0002_auto_20170419_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ContractDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='products',
            name='EndContractDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
