# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0003_auto_20170420_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='EndContractDate',
            field=models.DateField(),
        ),
    ]
