# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0004_auto_20170420_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
    ]
