# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternetBanking', '0005_products_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Amount', models.IntegerField()),
                ('MobileOperatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.MobileOperators')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operations',
            name='OperationCost',
            field=models.IntegerField(default=0),
        ),
    ]
