# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0005_auto_20170331_1225'),
        ('InternetBanking', '0004_applications_operations_userapplication_useroperations'),
    ]

    operations = [
    ]
