# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0006_auto_20170425_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='OperationCost',
            field=models.IntegerField(),
        ),
    ]
