# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternetBanking', '0009_auto_20170425_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.CharField(max_length=15)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternetProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='internetpay',
            name='InternetProviderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.InternetProviders'),
        ),
        migrations.AddField(
            model_name='internetpay',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Products'),
        ),
        migrations.AddField(
            model_name='internetpay',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
