# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternetBanking', '0010_auto_20170426_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=25)),
                ('Amount', models.IntegerField()),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Products')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
