# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0014_auto_20170510_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermoneyachive',
            name='ProductId',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='InternetBanking.Products'),
        ),
    ]
